### PR TITLE
Prometheus flags passed by env variable

### PR DESCRIPTION
**Pull request by gutorc92**
Prometheus log level equal promster log level

Signed-off-by: Gustavo Coelho <gutorc@hotmail.com>

### CODE REVIEW

**Comment by abilioesteves** [comment]
@gutorc92, if I'm not mistaken, prometheus env variables do NOT get overridden by promster's variables. I don't think a special env for that is necessary. Could you test it?

**Comment by abilioesteves** [comment]
@gutorc92, now I understand better your needs. But first, did you check if you are perhaps sharing the mounted volume with other containers? That's usually the cause for the lockfile conflict.

**Comment by gutorc92** [comment]
@abilioesteves, just Promster pods uses the mounted volume because it is linked to pod by a unique name. I think the problems is that the process to kill pods manually do not send a signal to Prometheus to remove the lockfile of the mounted volume.

**Comment by abilioesteves** [comment]
Oh, ok. That seems to be the real issue here. Activating the `nolockfile` option can be dangerous, you could endup with a dirty tsdb. We should investigate that further, maybe in another issue.

Maybe by forcing a `SIGKILL` signal to the prometheus process would do it?

**Comment by flaviostutz** [comment]
I'm with @abilioesteves. It is very dangerous to assume a "no-lock" behavior if you are not sure about what is happening with your volume.

**Pull request closed without merging**
